export const permissions = [
  { module: "dashboard", action: "view", code: "dashboard.view" },
  { module: "users", action: "view", code: "users.view" },
  { module: "users", action: "manage", code: "users.manage" },
  { module: "roles", action: "view", code: "roles.view" },
  { module: "roles", action: "manage", code: "roles.manage" },
  { module: "properties", action: "view", code: "properties.view" },
  { module: "properties", action: "manage", code: "properties.manage" },
  { module: "settings", action: "view", code: "settings.view" },
  { module: "settings", action: "manage", code: "settings.manage" },
  { module: "audit", action: "view", code: "audit.view" },
  { module: "accounting", action: "view", code: "accounting.view" },
  { module: "accounting", action: "manage_accounts", code: "accounting.accounts.manage" },
  { module: "accounting", action: "create_journal", code: "accounting.journals.create" },
  { module: "accounting", action: "post_journal", code: "accounting.journals.post" },
  { module: "front_office", action: "view", code: "front_office.view" },
  { module: "front_office", action: "manage_rooms", code: "front_office.rooms.manage" },
  { module: "front_office", action: "manage_guests", code: "front_office.guests.manage" },
  { module: "front_office", action: "create_reservation", code: "front_office.reservations.create" },
  { module: "front_office", action: "check_in", code: "front_office.reservations.check_in" },
  { module: "front_office", action: "check_out", code: "front_office.reservations.check_out" },
  { module: "pos", action: "view", code: "pos.view" },
  { module: "pos", action: "manage_outlets", code: "pos.outlets.manage" },
  { module: "pos", action: "manage_products", code: "pos.products.manage" },
  { module: "pos", action: "create_order", code: "pos.orders.create" },
  { module: "pos", action: "take_payment", code: "pos.orders.pay" },
  { module: "pos", action: "void_order", code: "pos.orders.void" },
  { module: "pos", action: "manage_shift", code: "pos.shifts.manage" },
  { module: "inventory", action: "view", code: "inventory.view" },
  { module: "purchasing", action: "view", code: "purchasing.view" },
  { module: "reports", action: "view", code: "reports.view" }
] as const;

export type PermissionCode = (typeof permissions)[number]["code"];
